# Generated by Django 4.0.3 on 2022-03-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('business_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('business_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
