# Generated by Django 4.0.3 on 2022-03-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vendordetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendordetails',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='vendordetails',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
