# Generated by Django 4.0.3 on 2022-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_location_vendordetails_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
