# Generated by Django 4.0.3 on 2022-04-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_regularuser_otp_regularuser_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='vendor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.vendor'),
            preserve_default=False,
        ),
    ]
