# Generated by Django 4.0.3 on 2022-04-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_vendordetails_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularuser',
            name='phone_number',
        ),
    ]
