# Generated by Django 4.0.3 on 2022-04-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_regularuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='vendor',
            name='certified',
            field=models.BooleanField(default=False),
        ),
    ]
