# Generated by Django 4.0.3 on 2022-04-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_vendor_phone_number_vendor_certified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetails',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='VendorDetails',
        ),
    ]
