# Generated by Django 4.0.3 on 2022-04-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('api', '0009_remove_vendordetails_vendor_alter_regularuser_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='vendor.vendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regularuser')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('identifier', models.CharField(blank=True, max_length=10, null=True)),
                ('tshirts', models.IntegerField(blank=True, null=True)),
                ('jeans', models.IntegerField(blank=True, null=True)),
                ('siglets', models.IntegerField(blank=True, null=True)),
                ('jackets', models.IntegerField(blank=True, null=True)),
                ('trousers', models.IntegerField(blank=True, null=True)),
                ('suits', models.IntegerField(blank=True, null=True)),
                ('blazers', models.IntegerField(blank=True, null=True)),
                ('skirts', models.IntegerField(blank=True, null=True)),
                ('blouses', models.IntegerField(blank=True, null=True)),
                ('ties', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regularuser')),
            ],
        ),
    ]
