# Generated by Django 4.0.3 on 2022-06-02 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='dat',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
