# Generated by Django 4.0.3 on 2022-06-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_order_date_order_dat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dat',
            new_name='date',
        ),
    ]
