# Generated by Django 4.0.3 on 2022-06-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_dat_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
